### PR TITLE
feat: add ArrowheadMatrix

### PR DESCRIPTION
**Pull request by Nimrais**
This PR introduces an efficient implementation of ArrowheadMatrix, a specialized matrix.

`ArrowheadMatrix` : Implements a memory-efficient representation of arrowhead matrices https://en.wikipedia.org/wiki/Arrowhead_matrix.

Basic Operations: Supports essential matrix operations like size, conversion to dense matrix, and multiplication with vectors.

Linear System Solving: Implements an efficient algorithm for solving linear systems involving arrowhead matrices.

Inverse Representation: Introduces InvArrowheadMatrix for representing the inverse of an ArrowheadMatrix without explicitly computing it.

Performance Optimizations: Utilizes the special structure of arrowhead matrices to achieve better time and space complexity compared to dense matrix operations.

Implementation Details

`ArrowheadMatrix`: Stores only the diagonal elements and the "arrow" parts of the matrix.
`mul!`: Optimized matrix-vector multiplication.
`linsolve!`: Efficient linear system solver tailored for arrowhead structure.
`InvArrowheadMatrix`: Lazy representation of the inverse, computing elements only when needed.

### CODE REVIEW

**Comment by wouterwln** [comment]
Can you recheck the PR? For example, this adds `BenchmarkTools` to the dependencies of BayesBase

**Comment by Nimrais** [comment]
@bvdmitri Yeah the structure is implemented but there is a nuance. Performance tests do not pass if you can help me or suggest me smt there it would be nice.

**Comment by Nimrais** [comment]
A strange thing that the results are just identical...

```
Expression: time_arrow < time_dense
   Evaluated: [-1.3740630832875642, 1.4274034155145767, -0.44621387932066114, 0.38904873887569447, 0.4987762756909691, 0.2010881126187817, -0.24356919905937316, -0.34356679981420757, 0.22869439509640563, -0.30901867983178133, -0.18884517711003823] < [-1.3740630832875642, 1.4274034155145765, -0.44621387932066114, 0.38904873887569447, 0.4987762756909691, 0.2010881126187817, -0.2435691990593732, -0.34356679981420757, 0.22869439509640563, -0.3090186798317814, -0.18884517711003823]
   ```
   
   [-1.3740630832875642, 1.4274034155145767, -0.44621387932066114, 0.38904873887569447, 0.4987762756909691, 0.2010881126187817, -0.24356919905937316, -0.34356679981420757, 0.22869439509640563, -0.30901867983178133, -0.18884517711003823]
   
   [-1.3740630832875642, 1.4274034155145765, -0.44621387932066114, 0.38904873887569447, 0.4987762756909691, 0.2010881126187817, -0.2435691990593732, -0.34356679981420757, 0.22869439509640563, -0.3090186798317814, -0.18884517711003823]

**Comment by wouterwln** [comment]
Yes those tests fail because of the `eltype` stuff that is in Distributions.jl that I referenced last week

**Review by wouterwln — APPROVED** [review]

**Comment by wouterwln** [comment]
@Nimrais can you double check coverage? I cannot see branch coverage and PR coverage. Maybe this is a problem with the bayesbase repo?

**Review by bvdmitri — APPROVED** [review]
Super nice work @Nimrais !!

**Pull request merged**
